PUT http://localhost:8080/events/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ4OTE3NDEwLCJ1c2VySWQiOjN9.v00WbGnzBPiZy5G9sxO1NSiDD-Xd0nAQpJDuRH_uDiE

{
    "Name": "Test Event 3.1",
    "Description": "Test Event 3.1",
    "Location": "A test location 3.1",
    "DateTime": "2025-06-03T15:00:00Z"
}